### ISSUE TITLE
Determine lock mechanism for automatic ingest of ePADD export

### ISSUE THREAD

**Issue by jessjass** [harvard-lts/epadd#100]
Call /ingest endpoint in DIMS only once for any epadd export picked up by curator app

**Comment by jessjass** [comment]
https://github.com/harvard-lts/epadd-curator-app/pull/1

**Comment by ives1227** [comment]
Resolution: https://github.com/harvard-lts/epadd-curator-app/commit/dc28aa102c9d68bc3ef80736c8a235405432477f
