### ISSUE TITLE
Create setup instruction manual

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#11]
As an end user, I would like to be able to set up the proper applications and dependencies on my computer.  This story includes setting up documentation around this.

**Comment by ives1227** [comment]
On hold because export is blocked.

**Comment by awoods** [comment]
In-process. Draft documentation in wiki?? - TBD, @juliewetherill .
More complete documentation pending end-to-end functionality of the tooling.

**Comment by juliewetherill** [comment]
Draft doc is here: https://docs.google.com/document/d/1jTOuHry1BTBTB2DdoLix1r87Dl2zfjsbandJjwDvKVE/edit?usp=sharing
