### ISSUE TITLE
Determine directory renaming strategy

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#110]
As a developer, I will need a way to identify each directory uniquely. ePADD currently exports the data into a 'user' directory.  This story is to finalize a renaming strategy for thee exported data.

What should it be renamed?
Where should it be renamed (S3 or dropbox)?

One risk factor is that the 'user' directory is not unique which may cause issues if the exported data is still in S3 and the user exports another packet.

**Comment by awoods** [comment]
@mztrz to explore the user documentation, and reach out to the ePADD developers if there is no apparent way within ePADD to configure the top-level export directory name.
Potentially, the LTS developers could investigate what code changes within ePADD would involve.

**Comment by jessjass** [comment]
@mztrz looked into the documentation and nothing found in them so will be reaching out to ePADD developers and users for more Information

**Comment by jessjass** [comment]
Directory is always named user/ and the ePADD+ team does not have bandwidth to make the change in their scope of work. The Harvard team may be able to make the change.

**Comment by jessjass** [comment]
The curators will have to export to a local directory and rename the export before uploading it to S3 via Nextcloud.

**Comment by awoods** [comment]
@jessjass : can you identify in the ePADD codebase where the directory naming would need to change?

**Comment by jessjass** [comment]
@awoods Sure I can see what I can find!
