### ISSUE TITLE
Transfer Service - Allow for Multiple s3 Buckets

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#113]

**Comment by ives1227** [comment]
PRs: 

https://github.com/harvard-lts/dais-transfer-service/pull/19
https://github.huit.harvard.edu/LTS/DAIS-IF/pull/41

**Comment by jessjass** [comment]
resolved with:
https://github.com/harvard-lts/dais-transfer-service/commit/2a3ac78230b15720e5cd03c99a6e8bad9ebab66c
https://github.huit.harvard.edu/LTS/DAIS-IF/commit/df4d3a1274850448e36ae58a526fb24ad7c902a1
