### ISSUE TITLE
Curator App needs to map drsConfig.txt file to DIMS request

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#115]
As a developer, I will need to map the sidecar drsConfig.txt file to the DIMS request.  Currently this data is hardcoded in the request to DIMS.

**Comment by jessjass** [comment]
PR: https://github.com/harvard-lts/epadd-curator-app/pull/2

**Comment by jessjass** [comment]
Resolved with: https://github.com/harvard-lts/epadd-curator-app/commit/da9265094937be2eef8f4950a7b7b7ad55e76932
