### ISSUE TITLE
Implement support gzip and 7zip in OTS

### ISSUE THREAD

**Issue by awoods** [harvard-lts/epadd#120]
This task is to determine if the level of effort required to update the OpaqueContainer content model to support gzip and 7zip would fit within a single sprint. 

If so, we should move forward in that direction; otherwise, we should consider the Opaque content model or other options.

OTS: https://github.huit.harvard.edu/LTS/ots/blob/8f7088e742c83ba8d8ed8aa91ee5327e1f28135f/src/main/java/edu/harvard/hul/ois/ots/contentmodels/OpaqueContainerObject.java#L22

Batch Builder:
https://github.huit.harvard.edu/LTS/batch_builder/blob/1bc28fa5bd4273604d8f0018dc9daa5f3352b9c5/conf/objectspecs/opaque%20container.xml#L36

**Comment by ghost** [comment]
Have submitted OTS PR for OpaqueContainer gzip and 7zip support.

https://github.huit.harvard.edu/LTS/ots/pull/10

**Comment by cvicary** [comment]
Merged PR: https://github.huit.harvard.edu/LTS/ots/commit/cba2c92af9a2d3f592a5a98d938465c12c257a90

**Comment by ghost** [comment]
Submitted PR to batch builder for gzip and 7zip support.

https://github.huit.harvard.edu/LTS/batch_builder/pull/7

Still investigating adding tests for this support.

@jessjass should this be reopened? Also, whom should I request review of batch builder?

**Comment by ghost** [comment]
Additional OTS PR required to support alternative gzip mime types, https://github.huit.harvard.edu/LTS/ots/pull/11.

Added test for opaque containers in batch builder, https://github.huit.harvard.edu/LTS/batch_builder/pull/7.

Pending approval, I believe this will satisfy this card.

**Comment by cvicary** [comment]
OTS changes merged: https://github.huit.harvard.edu/LTS/ots/commit/93d8dddc29d53260d630131a5500643229061c00

**Comment by jessjass** [comment]
Being deployed with current OTS release 1.0.60
