### ISSUE TITLE
Demo Phase1

### ISSUE THREAD

**Issue by awoods** [harvard-lts/epadd#13]
- Export from ePADD
- Identify package on file system
- Zip up the archive
- Create batch using Batch Builder on zipped archive (project will be set up ahead of time) **Make sure this is not set to sensitive for now
- Upload to dropbox
- Disconnect
- Login to Web Admin after Load report arrives and investigate the batch

**Comment by juliewetherill** [comment]
The video (7m15s) is on the project g drive, in the Video Demos folder.
https://drive.google.com/file/d/1XKI0Uho2784XR5UBtR5_d6Tmli7u25YI/view?usp=sharing
