### ISSUE TITLE
Identify content per owner code for migration

### ISSUE THREAD

**Issue by jessjass** [harvard-lts/epadd#17]
As a depositor, I would like to ensure that my existing content in EAS gets migrated properly.  The first step is identifying what content still exists in EAS.

**Comment by juliewetherill** [comment]
HUArchives content in EAS: https://docs.google.com/spreadsheets/d/19sgYYU6dNMRNzd4WqQzORjxPYgvQr0xw6jVFiPrKV9E/edit?usp=sharing

HUAM content in EAS: 
https://docs.google.com/spreadsheets/d/186nh6IgTuknuNYhJ7SWN4vHstGmMOOGZjZ0kCJhCY8s/edit?usp=sharing

**Comment by jessjass** [comment]
Review to be done by @mztrz and @slabrams
