### ISSUE TITLE
Design migration script for EAS to ePADD

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#21]
As a developer, once the depositors have determined what content should be moved from EAS to ePADD, I will need a script that will help to migrate the work.  This story is for the DESIGN of such a script.  Implementation will follow.

**Comment by awoods** [comment]
We will be giving HUA and HAM their content back from EAS. There will be no migration from EAS to ePADD.

**Comment by jessjass** [comment]
Not doing
