### ISSUE TITLE
Translate ePADD bag into Batch Builder data structure

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#26]
As a developer, I will need the data exported from ePADD to be formatted into a directory structure that Batch Builder will understand.

Mapping into OPAQUE_CONTAINER content model

**Comment by awoods** [comment]
This is phase2 work... is this ticket in phase1 for planning?

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/26?planning-poker) with ZenHub @juliewetherill @jessjass @awoods

**Comment by ives1227** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/26?planning-poker) with ZenHub @mztrz

**Comment by ives1227** [comment]
From Stephen: 

Here's a (rough;-) first draft of the requirements for mapping an ePADD export Bag into the directory structure of the OPAQUE content model.  No doubt, I've made some incorrect assumptions or left out important information, so please review and comment.  Thanks!
The document is attached as well as available on the shared Google drive: DRS Refresh Effort - Batch Builder Remediation - DRS Content Models > DRS Refresh > Specifications and Design, https://docs.google.com/document/d/1dx4Rh3Zgg9D1-_Ryaj34IWTijzvf7iJ4/edit

**Comment by ives1227** [comment]
Stephen - 
1. Can you confirm that we are still going to use opaque despite the possible caveats relating to rebuilding the directories?
2. Most of the missing values are in the drsConfig.sample.json file here: https://drive.google.com/file/d/1UcTFJigf66QGovEIOMWzGVPNndhvhMsO/view?usp=sharing

**Comment by awoods** [comment]
Leaning towards OPAQUE_CONTAINER... but concern on size limit (4GB) for zip. @mztrz to investigate impact of such a limitation (i.e. what are the expected upper ranges of bags/packets coming through ePADD). If necessary, we could explore use of other containers, i.e. gzip. - @slabrams to investigate how/why gzips are currently in the DRS.

@slabrams : Reason for existing gzips in the DRS:
- web-harvest content model (WAX gzips )
- OPAQUE content model supports any internal file formats.

**Comment by jessjass** [comment]
@juliewetherill to calculate original export + mbox size total

**Comment by jessjass** [comment]
EAS export sizes:
https://docs.google.com/spreadsheets/d/1uELO71Bol2O_hlLJmL33MNKOo3cDYhy5L7Rz6wKYAbE/edit?usp=sharing

Based on the large sizes of the exports, we will need to use 7zip or Gzip in either OPAQUE or OPAQUE_CONTAINER. If we use OPAQUE_CONTAINER, updates will need to be made in OTS - this seems like an easy lift, but will need @ives1227 's input.

**Comment by jessjass** [comment]
In OTS, we will be adding both Gzip and 7zip in order to use the OPAQUE_CONTAINER content model

**Comment by mztrz** [comment]
Within the curator app, we determined we wanted to select either Gzip or 7zip to package the ePADD exports for deposit into the DRS. Here are pros/cons of each:

[**Gzip:** ](https://www.gzip.org/)
- In production since 1992 and last stable release in 2022
- Better for when less memory is available, and compression/decompression speed is a concern

**[7zip](https://www.7-zip.org/)**
- In production since 1999, last release in 2022
- Bit more modern/sophisticated compression algorithm than gzip
- Uses more memory and time to compress/decompress so might be better solution when space is a concern and speed/compression speed isn't

**Comment by jessjass** [comment]
Tickets for work discussed in comments have been create to track work.
