### ISSUE TITLE
Gather sample exports from ePADD

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#45]

**Comment by ives1227** [comment]
IT Help is trying to unblock Julie's desktop from blocking exports.  ePADD has a way to write a properties file to allow for a different destination but Julie can't even get the properties file to write.  She is waiting on IT Help.

**Comment by juliewetherill** [comment]
Finally generated my first preservation export from EPadd+ on Mon 8/1. It is available from epadd+>Harvard LTS>Samples directory on the epadd project google drive: https://drive.google.com/drive/folders/1k6p1tf0367sNWG10y3X9uYHlWt8Sv6Q3?usp=sharing

**Comment by jessjass** [comment]
Document with various iterations of export testing from ePADD
https://docs.google.com/document/d/1eDcmnjo8dHo0Xlihj6QSczRf6AvtSb-AS7EYmczDtHA/edit#heading=h.ud6virjfq91
