### ISSUE TITLE
Integration test design for Curator App

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#54]
Integration tests will be in the HDC integration tests.

Have a dev container of the Curator App for testing.

API endpoint in Curator App that will simulate the ePADD export.

**Comment by jessjass** [comment]
Design document:
https://docs.google.com/document/d/15YVtuxmMcQ6ReKVufi3S2P--oxIyVUqQLRvSjbtd8b4/edit#heading=h.l2u1rd7b2tac
