### ISSUE TITLE
Curator App Implementation

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#58]
As a depositor, I would like to be able to have my ePADD exports automatically deposited into the DRS.  The implementation should be based on the design created in a previous sprint.

- Container that has cron and python
- Cron will monitor the s3 bucket(s)
  -  Cron will use the Node.js template
  - Triggers the Python script 
  -

- Python script
  - (possibly) a configuration file with the list of buckets
  - Check if the manifest exists. If so, the bag is ready to be moved
  - Makes an https request to DIMS with the bucket name and bag name and all of the necessary metadata (see below)
  - Healthcheck endpoint (see https://github.com/harvard-lts/drs-translation-service/blob/main/app/__init__.py)
  - Endpoint for integration test

```
{
     “package_id”: //string - see what makes the most sense for ePADD
     “s3_path”: //string
     “s3_bucket_name”: //string
     “admin_metadata”:
          {
             "accessFlag": "N",
              "contentModel": "opaque", -> or is it opaque-container ?
              "depositingSystem": "ePADD", -> Need check DIMS config to make sure ePADD is a valid depositing agent
              "firstGenerationInDrs": "unspecified",
              "objectRole": "CG:EMAIL",
              "usageClass": "LOWUSE",
              "storageClass": "AR",
              "ownerCode": "123",
              "billingCode": "456",
              "resourceNamePattern": "{n}",
              "urnAuthorityPath": "path",
              "depositAgent": "789",
              "depositAgentEmail": "someone@mailinator.com",
              "successEmail": "winner@mailinator.com",
              "failureEmail": "loser@mailinator.com",
              "successMethod": "all",
              "adminCategory": "root"
          }
}
```

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/58?planning-poker) with ZenHub @awoods @jessjass @juliewetherill

**Comment by ives1227** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/58?planning-poker) with ZenHub @mztrz

**Comment by awoods** [comment]
We may want to break this into smaller, incremental stories.

**Comment by ives1227** [comment]
@awoods , @jessjass and I are finalizing the design today.  If it is bigger than we anticipated, we will break it into smaller stories.  Otherwise, we'll make sure it has more details in the description after today.

**Comment by ives1227** [comment]
PR: https://github.com/harvard-lts/epadd-curator-app/pull/1

**Comment by jessjass** [comment]
https://github.com/harvard-lts/epadd-curator-app/pull/1

**Comment by ives1227** [comment]
Resolution: https://github.com/harvard-lts/epadd-curator-app/commit/dc28aa102c9d68bc3ef80736c8a235405432477f
