### ISSUE TITLE
Emailchemy licensing

### ISSUE THREAD

**Issue by slabrams** [harvard-lts/epadd#6]

**Comment by slabrams** [comment]
Reach out to Weird Kid to determine if a site license or embeddable license is possible.
https://weirdkid.com/emailchemy/
sales@weirdkid.com

**Comment by slabrams** [comment]
Consult with Ian about his conversation with Weird Kid

**Comment by slabrams** [comment]
Determine who in HUIT is responsible for software licensing

**Comment by ives1227** [comment]
Weird Kid is not responding to requests to meet.  Tricia will keep trying.

**Comment by ives1227** [comment]
Meeting with Matt from WK on Friday, September 9.

**Comment by awoods** [comment]
Discussed with ePADD+ partners meeting. @mztrz communicating embedded expectations with WK. Response from WK expected in the first two weeks of Oct.

**Comment by jessjass** [comment]
Emailchemy licensing has been agree upon but integration with ePADD has not yet been released
