### ISSUE TITLE
Modify DRS Transfer Integration Tests

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#61]
For changes to the dropbox location which is currently set in the .env

**Comment by jessjass** [comment]
PRs:
https://github.com/harvard-lts/dais-integration-tests/pull/14
https://github.huit.harvard.edu/LTS/DAIS-IF/pull/39

**Comment by ives1227** [comment]
Resolution: https://github.com/harvard-lts/dais-integration-tests/commit/281e481078b19732d3dbae2418d63b4e620a69e9
