### ISSUE TITLE
Define ePADD+ sidecar requirements

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#71]
As a developer, I will need to know where sidecar files will be coming out of ePADD and how it is expected that these files get moved into the DRS.

**Comment by awoods** [comment]
ePADD 9.0 release scheduled for second week of Oct... which will support sidecar files.
@mztrz to ask ePADD developers where sidecar file(s) will be in the export directory.
- There is concern about creation of the sidecar file... and the possibility of invalid DIMS files if created by curators.

Sidecar files will include: DIMS-file, and potentially others (e.g. rights agreements).

**Comment by awoods** [comment]
@jessjass to create a document that defines the data elements needed in the DIMS file.

**Comment by mztrz** [comment]
The files will be in C:\Users\<username>\epadd-appraisal\user\data\blobs\sidecarfiles\ 

File names will remain unchanged.

**Comment by jessjass** [comment]
Document for definition of the DRS sidecar file: https://docs.google.com/document/d/1jq3L2kFsUnl8tvy2EPxHIoQZNlXxxEqNsQr92Ui57N4/edit?usp=sharing

**Comment by jessjass** [comment]
The DRS File will be a text file with the format of <Field>=<Value>, and the curator app will parse and use this data in request body to DIMS. Finalized format of the sidecar file is included in the following doc: https://docs.google.com/document/d/1jq3L2kFsUnl8tvy2EPxHIoQZNlXxxEqNsQr92Ui57N4/edit#
