### ISSUE TITLE
Define metadata mapping requirements

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#72]
As a developer, I will need to know what metadata needs to be set for the exported ePADD content.  Will a file be supplied by ePADD that defines this?  Will we need to set this file in the automated DRS ingest system?  Should it be set in the Curator App?

This story is to define WHAT metadata needs to be set and WHERE in the pipeline this data will be set (what application is responsible for setting it?).

Robin should be included in this discussion.

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/72?planning-poker) with ZenHub @awoods @jessjass @juliewetherill @mztrz

**Comment by ives1227** [comment]
Tricia will determine the content model (opaque and opaque container)
Robin will make a first pass at the mapping
Robin will set up the adminCategory 'ePADD' field in Wordshack
Admin MD will come from a sidecar document that is provided along with the ePADD export.

**Comment by rwendler** [comment]
This is essentially "done as far as it can be done until we have a firm ePADD export package and firm DRS target." There are outstanding questions about 1) where the EAD metadata will be put in the ePADD export and an identifier for the ePADD export, 2) reconsideration of the target content model and/or how to preserve the ePADD directory structure as a machine-readable file in the opaque model, and 3) what form the configuration info for DRS should take (json, XML, TSV, etc.).

**Comment by ives1227** [comment]
https://docs.google.com/document/d/1C9sfdg0eIlsyg_EyhGjkiJyrR_cjgs7_/edit
https://docs.google.com/spreadsheets/d/13JPSFfmUXSMZCj56LJ1F9iWogDzgzpX2pOtSy7vygn4/edit#gid=0
