### ISSUE TITLE
SDS - transfer s3delivery proxy to use s3 pather

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#79]
As a developer, I will need SDS to pull the correct S3 path from an OCFL aware application.  The S3DeliveryProxy was a temporary application that assumes the path exists in S3.  The S3Pather pulls the path directly from S3.  SDS will need to be switched to use the S3Pather for reliability.

Currently, the S3Pather is not in prod but will be deployed as part of the https://github.huit.harvard.edu/LTS/MDS-ActiveMQ-IF project.  Katie will be managing the deployment: https://jira.huit.harvard.edu/browse/LTSMPS-13

**Comment by ives1227** [comment]
Had to modify s3pather to use a network in order for sds to communicate.  Still working on getting that logic correct.

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/79?planning-poker) with ZenHub @awoods @jessjass @juliewetherill @mztrz

**Comment by ives1227** [comment]
This may potentially have to get moved to the iceblock because of some outstanding questions remaining about the s3pather:

- This object https://drs2-qa.hul.harvard.edu/drs2_webadmin/file?fileId=401425944#summary is a playlist that has one file in it: urn-3:HBS.Baker.GEN:5069562017. If I look that up in Web Admin, I get the expected file object: https://drs2-qa.hul.harvard.edu/drs2_webadmin/file?fileId=401425937

- If I use the deliveryS3Proxy (http://ltsds-cloud-qa-1.lib.harvard.edu:23097/api/lookup/401425937), the NSSPath has the expected path to the mp3: /4596/0500/506954/v00001/content/data/401425937.mp3

- If I use s3pather (https://ltsds-cloud-qa-1.lib.harvard.edu:10892/s3pather/URN-3:HUL.DRS.OBJECT:506954/401425937), the top path is an unexpected wav file and the expected path is buried in the metadata section under the file.

- It is hard to decipher where it might land because the playlist (https://ltsds-cloud-qa-1.lib.harvard.edu:10892/s3pather/URN-3:HUL.DRS.OBJECT:506959/401425944) is at the top level and not under the metadata.

Question sent to iiif-services: Is this the expected behavior of the s3pather?

**Comment by ives1227** [comment]
Ticket opened here by Katie: https://jira.huit.harvard.edu/browse/LTSIIIF-1295

**Comment by awoods** [comment]
Resolved in previously noted ticket: https://jira.huit.harvard.edu/browse/LTSIIIF-1295
