### ISSUE TITLE
Evaluate nextcloud for ePADD exports

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#82]
As a developer, I would like to make the export of the ePADD to a next cloud secure S3 bucket.  This story is to evaluate whether this is a possibility by setting up next cloud and mounting it to our machines to test.

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/82?planning-poker) with ZenHub @awoods @juliewetherill @jessjass @mztrz

**Comment by awoods** [comment]
@ives1227 / @jessjass : If you have not already done so, as an initial step, please request a NextCloud account from Ops (Rei). Emily and Maureen may also be helpful.

**Comment by ives1227** [comment]
@awoods do you think we should wait until our meeting with Rei next Tuesday?

**Comment by awoods** [comment]
Sure, the request can wait until the Tuesday/Rei meeting.

**Comment by ives1227** [comment]
This has been successful.  Demo here: https://drive.google.com/file/d/1BcNgTjEXfMrWWzJFiZtMrToK481fMr4_/view?usp=sharing

Nextcloud installation instructions: https://docs.google.com/document/d/1inBe0pyDelhSjoN_qubXGEb1Uwo47Y57HR6nUSAcdik/edit

Nextcloud reconnection demo: https://drive.google.com/file/d/1tDLJimPE88efW2pqimYHrtbsKf44eiGn/view?usp=sharing
