### ISSUE TITLE
Add BB 2.3.0 to ACORN-DRS

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#86]
https://jira.huit.harvard.edu/browse/LIBDRS-8821

As an ACORN depositor, I would like my ACORN deposits to continue smoothly upon the DRS cutover.  This requires that BB 2.3.0 be placed into the ACORN DRS application.

This requires building a new ACORN image with BB 2.3.0 and pushing it to the registry.

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ePADD-Harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/86?planning-poker) with ZenHub @awoods @jessjass @juliewetherill @mztrz

**Comment by ives1227** [comment]
This may not get completed.  Details are in main JIRA ticket

**Comment by awoods** [comment]
@ives1227 : It is not clear based on either:
- https://jira.huit.harvard.edu/browse/LIBDRS-8821 or
- https://jira.huit.harvard.edu/browse/LTSMAINT-492

..what the blocker to getting this done may be.

**Comment by ives1227** [comment]
@awoods 492 is blocking 8821.  The blocker is time.  I do not have the time needed (days? maybe a week?) to get 492 finished.  I tried it during the maintenance sprint and I spent about 3 hours on it today realizing it was not happening in a short time.  I left instructions on 492 on what has to be done.

**Comment by awoods** [comment]
Thanks, @ives1227 .

**Comment by ives1227** [comment]
Closing since this may not get done by me.  I'll reopen if it changes.
