### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#87]
Successful export of ePADD to nextcloud S3 bucket
Demonstration of Curator App triggering DIMS to move data to the dropbox

**Comment by ives1227** [comment]
Exporting to S3 via Nextcloud: https://drive.google.com/file/d/1BcNgTjEXfMrWWzJFiZtMrToK481fMr4_/view?usp=sharing

**Comment by jessjass** [comment]
Curator app: https://drive.google.com/file/d/1PUpGV9xAgjXvbmp3q2AHt0wo5FjzP-V4/view?usp=sharing
