### ISSUE TITLE
Set up Curator App keys in DIMS

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#88]
As a developer, I would expect the Curator App to be allowed to trigger the DIMS API for setting off the ingest.  This requires keys to be set up.  DVN has a set of keys and now the Curator App will need a set.  More logic in DIMS may be needed to know which key to check based on the application name.

**Comment by ives1227** [comment]
Jessi will create for dev and QA and add to IF project.

**Comment by jessjass** [comment]
PR: https://github.huit.harvard.edu/LTS/DAIS-IF/pull/37

**Comment by ives1227** [comment]
Resolution: https://github.huit.harvard.edu/LTS/DAIS-IF/commit/97001b575a436ae704df2a35c15307953cf30672
