### ISSUE TITLE
Update DAIS Cron to handle multiple dropboxes

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#92]
Environment variables
Making sure the cron looks at all of the dropboxes in a list.

Example of if-else for setting some parameters in the translation service:
 
https://github.com/harvard-lts/drs-translation-service/blob/a50c39764340ad8c939667b205f27b6054565c6b/app/translation_service/translate_data_structure_service.py#L20-L26

Example of using the base dropbox location and list of dropbox names to loop through (so we only loop through specific dropboxes):

https://github.com/harvard-lts/drs-translation-service/blob/a50c39764340ad8c939667b205f27b6054565c6b/app/load_report_service/load_report_service.py#L26-L35

**Comment by jessjass** [comment]
PRs:
https://github.huit.harvard.edu/LTS/DAIS-IF/pull/38
https://github.com/harvard-lts/dais-cron/pull/9

**Comment by ives1227** [comment]
Resolution: https://github.com/harvard-lts/dais-cron/commit/61d3cdb24f17fb0fa3ef3a107aff2312be99e84c

https://github.huit.harvard.edu/LTS/DAIS-IF/commit/ce96c11c693d69480818e604a42955f57cc97943
